language: go

go:
  - "1.13.x"
  - "1.14.x"
  - "1.15.x"
  - "master"

os:
  - linux

go_import_path: github.com/axiaoxin-com/pink-lady

env:
  - GO111MODULE=on

services:
  - mysql
  - postgresql
  - redis

before_install:
  - cd src

install:
  - go mod tidy

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic -v ./...
